### ISSUE TITLE
Attach conditions to MessageKit, RetrievalKit,  ReencryptionRequest

### ISSUE THREAD

**Issue by theref** [nucypher/nucypher-core#19]
- Bump protocol versions for those objects
- Enrico signs conditions data and includes signature in the MessageKit?

**Comment by derekpierre** [comment]
Related to https://github.com/nucypher/tdec/issues/20.

**Comment by arjunhassard** [comment]
Faked in nucypher/nucypher/pull/2953

**Comment by derekpierre** [comment]
Using a shim layer on the python side (https://github.com/nucypher/nucypher/pull/2953) is the simplest move for now. Having to update the Rust layer (`nucypher-core`) takes time requires a build version, and dependency update etc.

The demo will use shim objects on the Python side which can be easily modified, so until an hardened architecture takes shap, modifying the Python layer is the easiest for now. Once a developed architecture comes into focus from the Python side, then the updates can be carried out in the Rust layer.

I think this issue can be iceboxed for now until later on.  (cc @arjunhassard )

**Comment by jMyles** [comment]
For the moment, we're slapping a `conditions` field on the `MessageKit` struct and calling it a day.  

We've also considered a separate struct for `ConditionsMessageKit` (or a different taxonomical division in message kits).

**Comment by derekpierre** [comment]
@theref can this issue be closed, given https://github.com/nucypher/nucypher-core/pull/26?

**Comment by theref** [comment]
Yes!
