### ISSUE TITLE
Should we be using `Option<&Conditions>` for nucypher-core cbd/dkg related objects

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher-core#76]
Conditions aren't really optional, why do we use `Option<&Conditions>` as parameters for various dkg protocol objects? Shouldn't it accept `Conditions` instead? No `Condition` is not an option for dkg (it was optional for PRE adapted tDec), we actually always want conditions.

cc @piotr-roslaniec , @KPrasch .

**Comment by piotr-roslaniec** [comment]
It's probably an overlooked artifact of the PRE CBD implementation. My guess is that we're already providing conditions everywhere, so we didn't detect this issue (which is purely in the API definition).

**Comment by KPrasch** [comment]
I agree, this is a historical artifact.  However, how will we support "vanilla PRE" without conditions?  Or perhaps we don't support that anymore?

**Comment by jdbertron** [comment]
PRE is valuable. A sentinel value would be good.

**Comment by derekpierre** [comment]
> It's probably an overlooked artifact of the PRE CBD implementation. My guess is that we're already providing conditions everywhere, so we didn't detect this issue (which is purely in the API definition).

Agreed.

> I agree, this is a historical artifact. However, how will we support "vanilla PRE" without conditions? Or perhaps we don't support that anymore? A sentinel value?

It's more so for CBD objects/structs in `nucypher-core` for which conditions should not be optional.  At a minimum, we can achieve that. I'm less concerned with changing PRE objects - and to be honest, I'd rather we don't as a safety measure - so it's fine if we leave Conditions as optional for PRE objects, but they should not be optional for CBD objects.

That being said, I thought we wanted to remove PRE-tdec code anyway...in other words, PRE will be just PRE and without conditions, at least from the `nucypher-ts` API side. In other words, even with conditions being optional for PRE objects in `nucypher-core`, `nucypher-ts` would not allow conditions to be specified for PRE anyway.

**Comment by piotr-roslaniec** [comment]
So perhaps we need a seperate API for PRE related activities, i.e. correctly describe where conditions are required and where they aren't.

**Comment by derekpierre** [comment]
> So perhaps we need a seperate API for PRE related activities, i.e. correctly describe where conditions are required and where they aren't.

My assumption here was that this would be part of removing the PRE-tdec work...basically, what's the minimal amount of work we can do to continue to support PRE after removing PRE-tdec. However, I'm still catching up on what's been going on since I left, and perhaps this has been discussed by others - not sure where this stands in the priority ordering. Of course PRE can be used with PRE-tdec code, just without any conditions.

**Comment by piotr-roslaniec** [comment]
I didn't catch this while working on removing PRE-tDec, but I agree with the premise. IMHO priorities are such that we can stabilize PRE API after TACo API is released, i.e. around 8.0.0. This is just my 2 cents. I'll be up for discussing this further and scoping.

**Comment by derekpierre** [comment]
At the very least, I'm going to fix this for CBD/DKG `nucypher-core` objects - trying not to touch PRE code at the moment.

**Comment by derekpierre** [comment]
Closed via #80 for CBD.
